config/routes.rb
Five::Application.routes.draw do
  resources :events

  resources :locations

  resources :groups do
    member do
      post 'join'
    end
  end

  resources :playings

  resources :games

  devise_for :users

  namespace :admin do
    resources :accounts
    resources :videos do
      member do
        post 'change_category'
      end
    end
    resources :categories
    resources :users
    resources :questions

    root to: 'accounts#index'
  end

  get 'profiles/:id' => 'users#show', as: :profile
  get 'users' => 'users#index', as: :users
  put 'users/:id' => 'users#update', as: :update_user
  post 'users/:id/invite' => 'users#invite', as: :invite_user

  delete 'invites/:id' => 'invites#destroy', as: :destroy_invite

  root 'home#index'

  match '/about' => 'home#about', via: :get, as: :about
  match '/contact' => 'home#contact', via: :get, as: :contact

  

end

app/models/group.rb
class Group < ActiveRecord::Base
  include IndexQuery

  has_many :invites

  has_and_belongs_to_many :games
  has_and_belongs_to_many :events

  has_many :groupings
  has_many :users, through: :groupings

  def self.users_groups(user)
    select('groups.*',
      'groupings.created_at AS user_join_date',
      'locations.city AS city', 'locations.state AS state').
    joins(%{
      INNER JOIN "groupings" ON "groupings"."group_id" = "groups"."id" AND "groupings"."user_id" = #{user.id}
      LEFT JOIN "locations" ON "locations"."group_id" = "groups"."id"
    })
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :join]
  before_action :set_group, only: [:show, :edit, :update, :destroy, :join]

  # GET /groups
  # GET /groups.json
  def index
    current_user = user_signed_in? ? current_user : nil
    @errors,@groups,@within,@order_them,@loc,@zip,@games,@selected_games = Group.index(params,current_user)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @users = User.group_members(@group)
    @games = Game.all

    if user_signed_in?
      @grouping = Grouping.where(user_id:current_user.id,group_id:@group.id).first
    end

    if @grouping && @grouping.admin
      @invitations = Invite.where(group_id:@group.id)
    end

    @location = @group.location
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  def join
    respond_to do |format|
      if @group.users << current_user
        format.json { render json: {} }
      else
        format.json { render json: {}, status: :unprocessable_entity }
      end
    end
  end

  def leave
    respond_to do |format|
      if @group.users.delete(current_user)
        format.json { render json: {} }
      else
        format.json { render json: {}, status: :unprocessable_entity }
      end
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name,:info)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for(@group, html: {class: 'form-horizontal', role: 'form'}) do |f|
  - if @group.errors.any?
    #error_explanation
      %h2
        = pluralize(@group.errors.count, "error")
        prohibited this group from being saved:
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, class: 'col-lg-2 control-label'
    .col-lg-3
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :info, class: 'col-lg-2 control-label'
    .col-lg-3
      = f.text_area :info, class: 'form-control', rows: 10
      %span.help-block Describe your group
  .actions
    = f.submit class: 'btn btn-primary'

app/views/groups/edit.html.haml
%h1 Editing group
= render 'form'
%br/
%p= link_to 'Show', @group

app/views/groups/index.html.haml
= render '/search', model:'group'

%table.table.table-striped#groups
  %thead
    %tr
      %th #
      %th Name
      %th Games played
      %th City
      %th Members
      - if @loc && @errors.empty?
        - if @order_them
          %th Distance away
        - else
          %th Distance from you
  %tbody
    - @groups.all.each_with_index do |group,index|
      - game_ids = group.preloaded_game_ids
      %tr{id: "group_#{group.id}", "data-game-id" => game_ids.join(',')}
        %td= index + 1
        %td= link_to group.name, group
        %td
          - if game_ids.any?
            - game = @games.find {|g| g.id == game_ids.first}
            = link_to game.name, game
            - if game_ids.length > 1
              - count = game_ids.length - 1
              - word = count > 1 ? 'others' : 'other'
              \& #{link_to "#{count.to_s} #{word}...", '#', class: 'moar_games tip', title: "Load the #{word}"}
        %td= link_to group.location.city, groups_path(city: group.location.city)
        %td= group.members_count
        - if @loc && @errors.empty?
          %td
            - if group.city
              = group.distance.round
              miles
            - else
              unknown

= link_to 'New Group', new_group_path, class: 'btn btn-primary'
:javascript
  $(function () {
    var games = new App.GameList(#{@games.to_json(except:[:created_at, :updated_at])}, {options:true})
    new App.SearchView({
      games: games,
      selected_game_ids: #{@selected_games.map {|g| g.id }}
    });

    new App.GroupsView({
      current_user_id: #{user_signed_in? ? current_user.id : "null"},
      games:games
    });
  })

app/views/groups/new.html.haml
%h1 New group
= render 'form'
= link_to 'Back', groups_path

app/views/groups/show.html.haml
%h3= @group.name
%h4 Info
.info
  = @group.info

%h4
  Members (#{@users.length})
  %small= link_to "Invite users", users_path(zip: @location ? @location.zip : nil, invite_group:@group.id)

- if @users.any?
  %table.table.table-striped#users
    %thead
      %tr
        %th #
        %th Name
        %th Games played
        %th City
        %th Last sign in
    %tbody
      - @users.each_with_index do |user,index|
        - game_ids = user.preloaded_game_ids
        %tr{id: "user_#{user.id}", class: user.is_group_admin ? 'success' : '', "data-game-id" => game_ids.join(',')}
          %td= index + 1
          %td= link_to user.name, profile_path(user)
          -
          %td
            - if game_ids.any?
              - game = @games.find {|g| g.id == game_ids.first}
              = link_to game.name, game
              - if game_ids.length > 1
                - count = game_ids.length - 1
                - word = count > 1 ? 'others' : 'other'
                \& #{link_to "#{count.to_s} #{word}...", '#', class: 'moar_games tip', title: "Load the #{word}"}
          %td
            - if user.city
              = link_to user.city, users_path(zip: user.zip)
            - else
              unknown

          %td= user.current_sign_in_at ? "#{time_ago_in_words(user.current_sign_in_at)} ago" : 'never signed in'

-if @grouping && @grouping.admin
  #invitations
    %h4
      Open invitations (<span class='invite_count'>#{@invitations.length}</span>)
      %small= link_to "Invite users", users_path(zip: @location ? @location.zip : nil, invite_group:@group.id)
    - if @invitations.any?
      %table.table.table-striped#invites
        %thead
          %tr
            %th #
            %th Sent
            %th Invitee
            %th Inviter
            %th Actions
        %tbody
          - @invitations.each_with_index do |invite,index|
            %tr{id: "invite_#{invite.id}"}
              %td= index + 1
              %td
                = time_ago_in_words(invite.created_at)
                ago
              %td
                - invitee = User.find invite.invitee_id
                = link_to invitee.name, profile_path(invitee)
              %td
                - inviter = User.find invite.user_id
                = link_to inviter.name, profile_path(inviter)
              %td
                = link_to 'revoke', '#', class: 'revoke_invite'


- if @grouping && @grouping.admin
  = link_to 'Edit', edit_group_path(@group)

:javascript
  $(function () {
    var games = new App.GameList(#{@games.to_json(except:[:created_at, :updated_at])}, {options:true})
    new App.UsersIndexView({games:games});
    new App.InvitesIndexView();
  })