config/routes.rb
Five::Application.routes.draw do
  resources :events

  resources :locations

  resources :groups do
    member do
      post 'join'
    end
  end

  resources :playings

  resources :games

  devise_for :users

  namespace :admin do
    resources :accounts
    resources :videos do
      member do
        post 'change_category'
      end
    end
    resources :categories
    resources :users
    resources :questions

    root to: 'accounts#index'
  end

  get 'profiles/:id' => 'users#show', as: :profile
  get 'users' => 'users#index', as: :users
  put 'users/:id' => 'users#update', as: :update_user
  post 'users/:id/invite' => 'users#invite', as: :invite_user

  delete 'invites/:id' => 'invites#destroy', as: :destroy_invite

  root 'home#index'

  match '/about' => 'home#about', via: :get, as: :about
  match '/contact' => 'home#contact', via: :get, as: :contact

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  include IndexQuery

  has_many :statuses
  has_many :users, through: :statuses

  has_and_belongs_to_many :games
  has_and_belongs_to_many :groups

  validates :user_id, presence: true

  def self.all_events
    select('events.*', 'locations.city AS city',
           'locations.zip AS zip', 'array_agg(games.id) AS preloaded_game_ids').
    joins(%{
      LEFT JOIN "locations" ON "locations"."event_id" = "events"."id"
      LEFT JOIN "events_games" ON "events_games"."event_id" = "events"."id"
      LEFT JOIN "games" ON "games"."id" = "events_games"."game_id" }).
    group('events.id,locations.id')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    current_user = user_signed_in? ? current_user : nil
    @errors,@events,@within,@order_them,@loc,@zip,@games,@selected_games = Event.index(params,current_user)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @creator = User.find @event.user_id
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :about, :references, :when)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="field">
    <%= f.label :references %><br>
    <%= f.text_field :references %>
  </div>
  <div class="field">
    <%= f.label :when %><br>
    <%= f.date_select :when %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_form.html.haml
= form_for(@event, html: {class: 'form-horizontal', role: 'form'}) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :title, class: 'col-lg-2 control-label'
    .col-lg-3
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :about, class: 'col-lg-2 control-label'
    .col-lg-3
      = f.text_area :about, class: 'input', rows:15, cols:50
  .form-group
    = f.label :start_time, "Start", class: 'col-lg-2 control-label'
    .col-lg-7
      = f.datetime_select :start_time, ampm: true
  .form-group
    = f.label :finish_time, "Finish", class: 'col-lg-2 control-label'
    .col-lg-7
      = f.datetime_select :finish_time, ampm: true
  .actions
    = f.submit class: 'btn btn-primary'

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/edit.html.haml
%h2 Editing event

= render 'form'

%br

= link_to 'Show', @event

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>About</th>
      <th>References</th>
      <th>When</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.about %></td>
        <td><%= event.references %></td>
        <td><%= event.when %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/index.html.haml
= render '/search', model:'event'

%h1
  Listing events
  %small= link_to 'New Event', new_event_path

%table.table.table-striped#events
  %thead
    %tr
      %th #
      %th Title
      %th About
      %th Games played
      %th City
      - if @loc && @errors.empty?
        %th City
      %th Start
      %th Finish
  %tbody
    - strf = '%-m/%-d/%y %l:%M %p'
    - @events.each_with_index do |event,index|
      - game_ids = event.preloaded_game_ids
      %tr{id: "event_#{event.id}", "data-game-id" => game_ids.join(',')}
        %td= index + 1
        %td= link_to event.title, event
        %td= event.about
        %td
          - if game_ids.any?
            - game = @games.find {|g| g.id == game_ids.first}
            = link_to game.name, game
            - if game_ids.length > 1
              - count = game_ids.length - 1
              - word = count > 1 ? 'others' : 'other'
              \& #{link_to "#{count.to_s} #{word}...", '#', class: 'moar_games tip', title: "Load the #{word}"}
        %td
          - if event.city
            = link_to event.city, events_path(zip: event.zip)
          - else
            unknown

        - if @loc && @errors.empty?
          %td
            - if event.city
              = event.distance.round
              miles
            - else
              unknown

        - if @invite_group
          %td
            - if user.id != current_user.id
              - if user.already_invited
                invited...
              - else
                = link_to "Invite", @invite_group, class: 'invite'

        %td= event.start_time.strftime(strf)
        %td= event.finish_time.strftime(strf)

:javascript
  $(function () {
    var games = new App.GameList(#{@games.to_json(except:[:created_at, :updated_at])}, {options:true})

    new App.SearchView({
      games: games,
      selected_game_ids: #{@selected_games.map {|g| g.id }}
    });

    new App.GroupsView({
      current_user_id: #{user_signed_in? ? current_user.id : "null"},
      games:games
    });
  })

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>About:</strong>
  <%= @event.about %>
</p>

<p>
  <strong>References:</strong>
  <%= @event.references %>
</p>

<p>
  <strong>When:</strong>
  <%= @event.when %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/show.html.haml
%h3= @event.title
%p
  %strong About:
  = @event.about

- strf = '%-m/%-d/%y %l:%M %p'
%p
  %strong Start:
  = @event.start_time.strftime(strf)

%p
  %strong Finish:
  = @event.finish_time.strftime(strf)

%p
  %strong Creator:
  = link_to @creator.name, profile_path(@creator)

- if user_signed_in? && current_user.owns_event?(@event)
  = link_to 'Edit', edit_event_path(@event)