config/routes.rb
Five::Application.routes.draw do
  resources :events

  resources :locations

  resources :groups do
    member do
      post 'join'
    end
  end

  resources :playings

  resources :games

  devise_for :users

  namespace :admin do
    resources :accounts
    resources :videos do
      member do
        post 'change_category'
      end
    end
    resources :categories
    resources :users
    resources :questions

    root to: 'accounts#index'
  end

  get 'profiles/:id' => 'users#show', as: :profile
  get 'users' => 'users#index', as: :users
  put 'users/:id' => 'users#update', as: :update_user
  post 'users/:id/invite' => 'users#invite', as: :invite_user

  delete 'invites/:id' => 'invites#destroy', as: :destroy_invite

  root 'home#index'

  match '/about' => 'home#about', via: :get, as: :about
  match '/contact' => 'home#contact', via: :get, as: :contact

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_and_belongs_to_many :groups
  has_and_belongs_to_many :events

  has_many :playings
  has_many :users, through: :playings

  validates :name, uniqueness: true
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < Admin::AdminController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :slug, :info)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      if params[:id].to_i > 0
        @game = Game.find(params[:id])
      else
        @game = Game.friendly.find params[:id]
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :slug, :about)
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def comma_separated_links_for(list)
    return if list.count == 0

    list.collect do |item|
      link_to(item.name, url_for(item)) 
     end.join(", ").html_safe
  end
end

app/views/games/_form.html.haml
= form_for(@game, html: {class: 'form-horizontal', role: 'form'}) do |f|
  - if @game.errors.any?
    #error_explanation
      %h2
        = pluralize(@game.errors.count, "error")
        prohibited this game from being saved:
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, class: 'col-lg-2 control-label'
    .col-lg-4
      = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :about, class: 'col-lg-2 control-label'
    .col-lg-9
      = f.text_field :about, class: 'form-control'
      %span.help-block A short blurb about the game
  .actions
    = f.submit class: 'btn btn-primary'

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

%br/
= link_to 'Show Game', @game
|
= link_to 'All Games', games_path

app/views/games/index.html.haml
%h3 Listing games

%table.table.table-striped#games
  %thead
    %tr
      %th #
      %th Name
      %th About
      %th Users playing
      %th
  %tbody
    - @games.all.each_with_index do |game,index|
      %tr{id:"game_#{game.id}"}
        %td= index + 1
        %td= link_to game.name, game
        %td= game.about
        %td= game.users.count
        %td= link_to "I play this game", '#', class: 'play_game'

= link_to 'Add a Game', new_game_path, class: 'btn btn-primary'

app/views/games/new.html.haml
%h1 New game

= render 'form'

= link_to 'All games', games_path

app/views/games/show.html.haml
%p
  %strong Name:
  = @game.name

%p
  %strong About:
  = @game.about

%p
  %strong Users playing:
  = @game.users.count
  = link_to "see users", users_path(games:@game.id)

%p
  %strong Groups playing:
  = @game.groups.count
  = link_to "see groups", groups_path(games:@game.id)

- if user_signed_in? && @game.user_id == current_user.id
  = link_to 'Edit', edit_game_path(@game)