config/routes.rb
Five::Application.routes.draw do
  resources :events

  resources :locations

  resources :groups do
    member do
      post 'join'
    end
  end

  resources :playings

  resources :games

  devise_for :users

  namespace :admin do
    resources :accounts
    resources :videos do
      member do
        post 'change_category'
      end
    end
    resources :categories
    resources :users
    resources :questions

    root to: 'accounts#index'
  end

  get 'profiles/:id' => 'users#show', as: :profile
  get 'users' => 'users#index', as: :users
  put 'users/:id' => 'users#update', as: :update_user
  post 'users/:id/invite' => 'users#invite', as: :invite_user

  delete 'invites/:id' => 'invites#destroy', as: :destroy_invite

  root 'home#index'

  match '/about' => 'home#about', via: :get, as: :about
  match '/contact' => 'home#contact', via: :get, as: :contact

  

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %title Five
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/

    %link{:href => "starter-template.css", :rel => "stylesheet"}/
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} Five
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to "Users", users_path
            %li= link_to "Games", games_path
            %li= link_to "Groups", groups_path
            %li= link_to "Events", events_path

          = render 'devise/menu/sign_in_crap'
        / /.nav-collapse
    .container
      = yield

app/views/layouts/corporate.html.haml
!!!
%html{:lang => "en"}
  %head
    %title Five
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "Board games website", :name => "description"}/
    %meta{:content => "Kmurph", :name => "author"}/

    %title Jumbotron Template for Bootstrap
    / Bootstrap core CSS
    / Custom styles for this template
    /[if lt IE 9]
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} Boardly
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li.active= link_to "Home", root_url
            %li= link_to "About", about_path
            %li= link_to "Contact", contact_path

          = render 'devise/menu/sign_in_crap'

    / Main jumbotron for a primary marketing message or call to action
    = yield
    %hr/
    %footer
      %p © DndSite 20ever